theme: jekyll-theme-minimal
title: Rewardsweb – Propuesta de Integración para Verifiers / Bancos
description: Este documento describe en 4 pasos cómo Rewardsweb sugiere conectarse con un Verifier o Banco para el flujo de integración y verificación de transacciones.