theme: jekyll-theme-minimal
title: Propuesta de Integraci贸n para Verificadores / Bancos
description: Este documento describe en 4 pasos c贸mo Rewardsweb sugiere conectarse con un Verificador o Banco para el flujo de integraci贸n y verificaci贸n de transacciones.